### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by jcmundy** [BCLibraries/mets-to-iiif#4]
I keep getting the following error when I try to run this.

```
/usr/local/lib/ruby/gems/2.4.0/gems/metsiiif-0.8.0/lib/metsiiif/builder.rb:23:in `block in build': undefined method `include?' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/metsiiif-0.8.0/lib/metsiiif/builder.rb:23:in `any?'
	from /usr/local/lib/ruby/gems/2.4.0/gems/metsiiif-0.8.0/lib/metsiiif/builder.rb:23:in `build'
	from /usr/local/lib/ruby/gems/2.4.0/gems/metsiiif-0.8.0/lib/metsiiif.rb:24:in `main'
	from /usr/local/lib/ruby/gems/2.4.0/gems/metsiiif-0.8.0/exe/metsiiif:5:in `<top (required)>'
	from /usr/local/bin/metsiiif:22:in `load'
	from /usr/local/bin/metsiiif:22:in `<main>'
```

**Comment by jazairi** [comment]
Hi @jcmundy, thanks for reporting this error. Could you share the METS file you're trying to transform?

**Comment by jcmundy** [comment]
Thanks. This is one METS file. It came with the image path (objectIdentifierValue) as ..\IMAGES\Output\ and I have tried it as that and as ../IMAGES/Output/
https://github.com/jcmundy/samplepage/blob/master/METS.xml

**Comment by jazairi** [comment]
I think this particular error might have to do with the value of `structmap` in config.yml. We rarely have multiple structMaps in our METS, so we don't specify `@TYPE`. You'd need to add `[@TYPE="physical"]` to the `structmap` config element so Nokogiri selects the correct structMap.

I can see a few other potential issues, too. For example, the gem requires a dmdSec that contains MODS. You might also run into issues with `MetsFile#sequence_label` and `MetsFile#struct_map` methods, both of which are looking for a specific type of value in the structMap div labels.

We wrote this gem for Boston College METS from our old DigiTool instance, so it will probably need a fair amount of tweaking to work with other METS application profiles. That said, if you'd like to create a fork to get it to work with your project, I'm happy to answer any questions you have about the codebase.

**Comment by jcmundy** [comment]
Thank you.
